define([], function () {
    return {
        ADD_TO_CART: 'ADD_TO_CART',
        CHECKOUT_REQUEST: 'CHECKOUT_REQUEST',
        CHECKOUT_SUCCESS: 'CHECKOUT_SUCCESS',
        CHECKOUT_FAILURE: 'CHECKOUT_FAILURE',
        RECEIVE_PRODUCTS: 'RECEIVE_PRODUCTS'
    };
});


